


function addScore() {
  const score1 = document.getElementById('score1').value
  const score2 = document.getElementById('score2').value
  const score3 = document.getElementById('score3').value
  const score4 = document.getElementById('score4').value
  const score5 = document.getElementById('score5').value
  const score6 = document.getElementById('score6').value
  const score7 = document.getElementById('score7').value
  const score8 = document.getElementById('score8').value
  const score9 = document.getElementById('score9').value
  const score10 = document.getElementById('score10').value
  const score11 = document.getElementById('score11').value
  const score12 = document.getElementById('score12').value
  const score13 = document.getElementById('score13').value
  const score14 = document.getElementById('score14').value
  const score15 = document.getElementById('score15').value
  const score16 = document.getElementById('score16').value
  const score17 = document.getElementById('score17').value
  const score18 = document.getElementById('score18').value
  const score19 = document.getElementById('score19').value
  const score20 = document.getElementById('score20').value
  const score21 = document.getElementById('score21').value
  const score22 = document.getElementById('score22').value
  const score23 = document.getElementById('score23').value
  const score24 = document.getElementById('score24').value
  const score25 = document.getElementById('score25').value
  const score26 = document.getElementById('score26').value
  const score27 = document.getElementById('score27').value
  const score28 = document.getElementById('score28').value
  const score29 = document.getElementById('score29').value
  const score30 = document.getElementById('score30').value
  const score31 = document.getElementById('score31').value
  const score32 = document.getElementById('score32').value
  const score33 = document.getElementById('score33').value
  const score34 = document.getElementById('score34').value
  const score35 = document.getElementById('score35').value
  const score36 = document.getElementById('score36').value
  const score37 = document.getElementById('score37').value
  const score38 = document.getElementById('score38').value
  const score39 = document.getElementById('score39').value
  const score40 = document.getElementById('score40').value
  const score41 = document.getElementById('score41').value
  const score42 = document.getElementById('score42').value
  const score43 = document.getElementById('score43').value
  const score44 = document.getElementById('score44').value
  const score45 = document.getElementById('score45').value
  const score46 = document.getElementById('score46').value
  const score47 = document.getElementById('score47').value
  const score48 = document.getElementById('score48').value
  const score49 = document.getElementById('score49').value
  const score50 = document.getElementById('score50').value
  const score51 = document.getElementById('score51').value
  const score52 = document.getElementById('score52').value
  const score53 = document.getElementById('score53').value
  const score54 = document.getElementById('score54').value
  const score55 = document.getElementById('score55').value
  const score56 = document.getElementById('score56').value
  const score57 = document.getElementById('score57').value
  const score58 = document.getElementById('score58').value
  const score59 = document.getElementById('score59').value
  const score60 = document.getElementById('score60').value
  const score61 = document.getElementById('score61').value
  const score62 = document.getElementById('score62').value
  const score63 = document.getElementById('score63').value
  const score64 = document.getElementById('score64').value
  const score65 = document.getElementById('score65').value
  const score66 = document.getElementById('score66').value
  const score67 = document.getElementById('score67').value
  const score68 = document.getElementById('score68').value
  const score69 = document.getElementById('score69').value
  const score70 = document.getElementById('score70').value
  const score71 = document.getElementById('score71').value
  const score72 = document.getElementById('score72').value
  const score73 = document.getElementById('score73').value
  const score74 = document.getElementById('score74').value
  const score75 = document.getElementById('score75').value
  const score76 = document.getElementById('score76').value
  const score77 = document.getElementById('score77').value
  const score78 = document.getElementById('score78').value
  const score79 = document.getElementById('score79').value
  const score80 = document.getElementById('score80').value
  const score81 = document.getElementById('score81').value
  const score82 = document.getElementById('score82').value
  const score83 = document.getElementById('score83').value
  const score84 = document.getElementById('score84').value
  const score85 = document.getElementById('score85').value
  const score86 = document.getElementById('score86').value
  const score87 = document.getElementById('score87').value
  const score88 = document.getElementById('score88').value
  const score89 = document.getElementById('score89').value
  const score90 = document.getElementById('score90').value
  const score91 = document.getElementById('score91').value
  const score92 = document.getElementById('score92').value
  const score93 = document.getElementById('score93').value
  const score94 = document.getElementById('score94').value
  const score95 = document.getElementById('score95').value
  const score96 = document.getElementById('score96').value
  const score97 = document.getElementById('score97').value
  const score98 = document.getElementById('score98').value
  const score99 = document.getElementById('score99').value
  const score100 = document.getElementById('score100').value
  const score101 = document.getElementById('score101').value
  const score102 = document.getElementById('score102').value
  const score103 = document.getElementById('score103').value
  const score104 = document.getElementById('score104').value
  const score105 = document.getElementById('score105').value
  const score106 = document.getElementById('score106').value
  const score107 = document.getElementById('score107').value
  const score108 = document.getElementById('score108').value
  const score109 = document.getElementById('score109').value
  const score110 = document.getElementById('score110').value
  const score111 = document.getElementById('score111').value
  const score112 = document.getElementById('score112').value
  const score113 = document.getElementById('score113').value
  const score114 = document.getElementById('score114').value
  const score115 = document.getElementById('score115').value
  const score116 = document.getElementById('score116').value
  const score117 = document.getElementById('score117').value
  const score118 = document.getElementById('score118').value
  const score119 = document.getElementById('score119').value
  const score120 = document.getElementById('score120').value
  const score121 = document.getElementById('score121').value
  const score122 = document.getElementById('score122').value
  const score123 = document.getElementById('score123').value
  const score124 = document.getElementById('score124').value
  const score125 = document.getElementById('score125').value
  const score126 = document.getElementById('score126').value
  const score127 = document.getElementById('score127').value
  const score128 = document.getElementById('score128').value









  const resultScore = { score1, score2, score3, score4, score5, score6, score7, score8, score9, score10, score11, score12, score13, score14, score15, score16, score17, score18, score19, score20, score21, score22, score23, score24, score25, score26, score27, score28, score29, score30, score31, score32, score33, score34, score35, score36, score37, score38, score39, score40, score41, score42, score43, score44, score45, score46, score47, score48, score49, score50, score51, score52, score53, score54, score55, score56, score57, score58, score59, score60, score61, score62, score63, score64, score65, score66, score67, score68, score69, score70, score71, score72, score73, score74, score75, score76, score77, score78, score79, score80, score81, score82, score83, score84, score85, score86, score87, score88, score89, score90, score91, score92, score93, score94, score95, score96, score97, score98, score99, score100, score101, score102, score103, score104, score105, score106, score107, score108, score109, score110, score111, score112, score113, score114, score115, score116, score117, score118, score119, score120, score121, score122, score123, score124, score125, score126, score127, score128 };




  if (localStorage.getItem('score') === null) {
    localStorage.setItem('score', JSON.stringify(resultScore));
  } else {
    localStorage.setItem('score', JSON.stringify(resultScore)
    );
  }


}

function loadScore() {
  const score1 = document.getElementById('score1')
  const score2 = document.getElementById('score2')
  const score3 = document.getElementById('score3')
  const score4 = document.getElementById('score4')
  const score5 = document.getElementById('score5')
  const score6 = document.getElementById('score6')
  const score7 = document.getElementById('score7')
  const score8 = document.getElementById('score8')
  const score9 = document.getElementById('score9')
  const score10 = document.getElementById('score10')
  const score11 = document.getElementById('score11')
  const score12 = document.getElementById('score12')
  const score13 = document.getElementById('score13')
  const score14 = document.getElementById('score14')
  const score15 = document.getElementById('score15')
  const score16 = document.getElementById('score16')
  const score17 = document.getElementById('score17')
  const score18 = document.getElementById('score18')
  const score19 = document.getElementById('score19')
  const score20 = document.getElementById('score20')
  const score21 = document.getElementById('score21')
  const score22 = document.getElementById('score22')
  const score23 = document.getElementById('score23')
  const score24 = document.getElementById('score24')
  const score25 = document.getElementById('score25')
  const score26 = document.getElementById('score26')
  const score27 = document.getElementById('score27')
  const score28 = document.getElementById('score28')
  const score29 = document.getElementById('score29')
  const score30 = document.getElementById('score30')
  const score31 = document.getElementById('score31')
  const score32 = document.getElementById('score32')
  const score33 = document.getElementById('score33')
  const score34 = document.getElementById('score34')
  const score35 = document.getElementById('score35')
  const score36 = document.getElementById('score36')
  const score37 = document.getElementById('score37')
  const score38 = document.getElementById('score38')
  const score39 = document.getElementById('score39')
  const score40 = document.getElementById('score40')
  const score41 = document.getElementById('score41')
  const score42 = document.getElementById('score42')
  const score43 = document.getElementById('score43')
  const score44 = document.getElementById('score44')
  const score45 = document.getElementById('score45')
  const score46 = document.getElementById('score46')
  const score47 = document.getElementById('score47')
  const score48 = document.getElementById('score48')
  const score49 = document.getElementById('score49')
  const score50 = document.getElementById('score50')
  const score51 = document.getElementById('score51')
  const score52 = document.getElementById('score52')
  const score53 = document.getElementById('score53')
  const score54 = document.getElementById('score54')
  const score55 = document.getElementById('score55')
  const score56 = document.getElementById('score56')
  const score57 = document.getElementById('score57')
  const score58 = document.getElementById('score58')
  const score59 = document.getElementById('score59')
  const score60 = document.getElementById('score60')
  const score61 = document.getElementById('score61')
  const score62 = document.getElementById('score62')
  const score63 = document.getElementById('score63')
  const score64 = document.getElementById('score64')
  const score65 = document.getElementById('score65')
  const score66 = document.getElementById('score66')
  const score67 = document.getElementById('score67')
  const score68 = document.getElementById('score68')
  const score69 = document.getElementById('score69')
  const score70 = document.getElementById('score70')
  const score71 = document.getElementById('score71')
  const score72 = document.getElementById('score72')
  const score73 = document.getElementById('score73')
  const score74 = document.getElementById('score74')
  const score75 = document.getElementById('score75')
  const score76 = document.getElementById('score76')
  const score77 = document.getElementById('score77')
  const score78 = document.getElementById('score78')
  const score79 = document.getElementById('score79')
  const score80 = document.getElementById('score80')
  const score81 = document.getElementById('score81')
  const score82 = document.getElementById('score82')
  const score83 = document.getElementById('score83')
  const score84 = document.getElementById('score84')
  const score85 = document.getElementById('score85')
  const score86 = document.getElementById('score86')
  const score87 = document.getElementById('score87')
  const score88 = document.getElementById('score88')
  const score89 = document.getElementById('score89')
  const score90 = document.getElementById('score90')
  const score91 = document.getElementById('score91')
  const score92 = document.getElementById('score92')
  const score93 = document.getElementById('score93')
  const score94 = document.getElementById('score94')
  const score95 = document.getElementById('score95')
  const score96 = document.getElementById('score96')
  const score97 = document.getElementById('score97')
  const score98 = document.getElementById('score98')
  const score99 = document.getElementById('score99')
  const score100 = document.getElementById('score100')
  const score101 = document.getElementById('score101')
  const score102 = document.getElementById('score102')
  const score103 = document.getElementById('score103')
  const score104 = document.getElementById('score104')
  const score105 = document.getElementById('score105')
  const score106 = document.getElementById('score106')
  const score107 = document.getElementById('score107')
  const score108 = document.getElementById('score108')
  const score109 = document.getElementById('score109')
  const score110 = document.getElementById('score110')
  const score111 = document.getElementById('score111')
  const score112 = document.getElementById('score112')
  const score113 = document.getElementById('score113')
  const score114 = document.getElementById('score114')
  const score115 = document.getElementById('score115')
  const score116 = document.getElementById('score116')
  const score117 = document.getElementById('score117')
  const score118 = document.getElementById('score118')
  const score119 = document.getElementById('score119')
  const score120 = document.getElementById('score120')
  const score121 = document.getElementById('score121')
  const score122 = document.getElementById('score122')
  const score123 = document.getElementById('score123')
  const score124 = document.getElementById('score124')
  const score125 = document.getElementById('score125')
  const score126 = document.getElementById('score126')
  const score127 = document.getElementById('score127')
  const score128 = document.getElementById('score128')




  const load = JSON.parse(localStorage.getItem('score'))


  if (load) {
    score1.value = load.score1
    score2.value = load.score2
    score3.value = load.score3
    score4.value = load.score4
    score5.value = load.score5
    score6.value = load.score6
    score7.value = load.score7
    score8.value = load.score8
    score9.value = load.score9
    score10.value = load.score10
    score11.value = load.score11
    score12.value = load.score12
    score13.value = load.score13
    score14.value = load.score14
    score15.value = load.score15
    score16.value = load.score16
    score17.value = load.score17
    score18.value = load.score18
    score19.value = load.score19
    score20.value = load.score20
    score21.value = load.score21
    score22.value = load.score22
    score23.value = load.score23
    score24.value = load.score24
    score25.value = load.score25
    score26.value = load.score26
    score27.value = load.score27
    score28.value = load.score28
    score29.value = load.score29
    score30.value = load.score30
    score31.value = load.score31
    score32.value = load.score32
    score33.value = load.score33
    score34.value = load.score34
    score35.value = load.score35
    score36.value = load.score36
    score37.value = load.score37
    score38.value = load.score38
    score39.value = load.score39
    score40.value = load.score40
    score41.value = load.score41
    score42.value = load.score42
    score43.value = load.score43
    score44.value = load.score44
    score45.value = load.score45
    score46.value = load.score46
    score47.value = load.score47
    score48.value = load.score48
    score49.value = load.score49
    score50.value = load.score50
    score51.value = load.score51
    score52.value = load.score52
    score53.value = load.score53
    score54.value = load.score54
    score55.value = load.score55
    score56.value = load.score56
    score57.value = load.score57
    score58.value = load.score58
    score59.value = load.score59
    score60.value = load.score60
    score61.value = load.score61
    score62.value = load.score62
    score63.value = load.score63
    score64.value = load.score64
    score65.value = load.score65
    score66.value = load.score66
    score67.value = load.score67
    score68.value = load.score68
    score69.value = load.score69
    score70.value = load.score70
    score71.value = load.score71
    score72.value = load.score72
    score73.value = load.score73
    score74.value = load.score74
    score75.value = load.score75
    score76.value = load.score76
    score77.value = load.score77
    score78.value = load.score78
    score79.value = load.score79
    score80.value = load.score80
    score81.value = load.score81
    score82.value = load.score82
    score83.value = load.score83
    score84.value = load.score84
    score85.value = load.score85
    score86.value = load.score86
    score87.value = load.score87
    score88.value = load.score88
    score89.value = load.score89
    score90.value = load.score90
    score91.value = load.score91
    score92.value = load.score92
    score93.value = load.score93
    score94.value = load.score94
    score95.value = load.score95
    score96.value = load.score96
    score97.value = load.score97
    score98.value = load.score98
    score99.value = load.score99
    score100.value = load.score100
    score101.value = load.score101
    score102.value = load.score102
    score103.value = load.score103
    score104.value = load.score104
    score105.value = load.score105
    score106.value = load.score106
    score107.value = load.score107
    score108.value = load.score108
    score109.value = load.score109
    score110.value = load.score110
    score111.value = load.score111
    score112.value = load.score112
    score113.value = load.score113
    score114.value = load.score114
    score115.value = load.score115
    score116.value = load.score116
    score117.value = load.score117
    score118.value = load.score118
    score119.value = load.score119
    score120.value = load.score120
    score121.value = load.score121
    score122.value = load.score122
    score123.value = load.score123
    score124.value = load.score124
    score125.value = load.score125
    score126.value = load.score126
    score127.value = load.score127
    score128.value = load.score128
  }
}

